const apartments =[
    {
    "id": 1,
    "img": "https://i.ibb.co/YTKzF0G/Rectangle-394.png", 
    "name": "Washington Avenue",
    "location": "Nasirabad H/S, Chattogram",
    "bedroom": " 3 Badrooms", 
    "bathroom":" 2 Bathrooms",
    "price" : 194,
    "img1" : "https://i.ibb.co/GRVkLTj/Rectangle-410.png",
    "img2" : "https://i.ibb.co/qCm8mmZ/Rectangle-407.png",
    "img3" : "https://i.ibb.co/R4Bn3qw/Rectangle-408.png", 
    "img4" : "https://i.ibb.co/PMfqvTC/Rectangle-409.png",
    "description": "3000 sq-ft, 3 bedrooms, semi-furnished, luxurious, south facing apartment for rent in nasirabad housing society, chittogong.",
    "priceDetails" : "Rent/Month : $550 (Negotiable) service Charge: 8000 tk per month, subject to change, security deposit: 3 month rent, Flat release policy: 3 months earlier notice required.  ",
    "property":" Address & area: Rang-malancha, house-#34, road-#24, nasirabad H/S, Chhittagong, flat size: 300 sq-ft, floor: A5(5th floor), room-category: 3 larg bed rooms, 2 bath rooms, 1 drawing, dining & family living room",
  },
    {
    "id": 2,
    "img": "https://i.ibb.co/ZTT2vkP/Rectangle-396.png", 
    "name": "Family Apartment three",
    "location": "Nasirabad H/S, Chattogram",
    "bedroom": " 3 Badrooms", 
    "bathroom":" 2 Bathrooms",
    "price" : 356,
    "img1" : "https://i.ibb.co/GRVkLTj/Rectangle-410.png",
    "img2" : "https://i.ibb.co/qCm8mmZ/Rectangle-407.png",
    "img3" : "https://i.ibb.co/R4Bn3qw/Rectangle-408.png", 
    "img4" : "https://i.ibb.co/PMfqvTC/Rectangle-409.png",
    "description": "3000 sq-ft, 3 bedrooms, semi-furnished, luxurious, south facing apartment for rent in nasirabad housing society, chittogong.",
    "priceDetails" : "Rent/Month : $550 (Negotiable) service Charge: 8000 tk per month, subject to change, security deposit: 3 month rent, Flat release policy: 3 months earlier notice required.  ",
    "property":" Address & area: Rang-malancha, house-#34, road-#24, nasirabad H/S, Chhittagong, flat size: 300 sq-ft, floor: A5(5th floor), room-category: 3 larg bed rooms, 2 bath rooms, 1 drawing, dining & family living room",
  },
  {
    "id": 3,
    "img": "https://i.ibb.co/7tshmmw/Rectangle-398.png", 
    "name": "Gorgeous House",
    "location": "Nasirabad H/S, Chattogram",
    "bedroom": " 3 Badrooms", 
    "bathroom":" 2 Bathrooms",
    "price" : 256,
    "img1" : "https://i.ibb.co/GRVkLTj/Rectangle-410.png",
    "img2" : "https://i.ibb.co/qCm8mmZ/Rectangle-407.png",
    "img3" : "https://i.ibb.co/R4Bn3qw/Rectangle-408.png", 
    "img4" : "https://i.ibb.co/PMfqvTC/Rectangle-409.png",
    "description": `3000 sq-ft, 3 bedrooms, semi-furnished, luxurious, south facing apartment for rent in nasirabad housing society, chittogong.`,
    "priceDetails" : `Rent/Month : $550 (Negotiable)
     service Charge: 8000 tk per month, subject to change,
      security deposit: 3 month rent, 
      Flat release policy: 3 months earlier notice required. `,
    "property":" Address & area: Rang-malancha, house-#34, road-#24, nasirabad H/S, Chhittagong, flat size: 300 sq-ft, floor: A5(5th floor), room-category: 3 larg bed rooms, 2 bath rooms, 1 drawing, dining & family living room",
  },
  {
    "id": 4,
    "img": "https://i.ibb.co/XYDJMd2/Rectangle-403.png", 
    "name": "Luxury Villa",
    "location": "Nasirabad H/S, Chattogram",
    "bedroom": " 3 Badrooms", 
    "bathroom":" 2 Bathrooms",
    "price" : 345,
    "img1" : "https://i.ibb.co/GRVkLTj/Rectangle-410.png",
    "img2" : "https://i.ibb.co/qCm8mmZ/Rectangle-407.png",
    "img3" : "https://i.ibb.co/R4Bn3qw/Rectangle-408.png", 
    "img4" : "https://i.ibb.co/PMfqvTC/Rectangle-409.png",
    "description": "3000 sq-ft, 3 bedrooms, semi-furnished, luxurious, south facing apartment for rent in nasirabad housing society, chittogong.",
    "priceDetails" : "Rent/Month : $550 (Negotiable) service Charge: 8000 tk per month, subject to change, security deposit: 3 month rent, Flat release policy: 3 months earlier notice required.  ",
    "property":" Address & area: Rang-malancha, house-#34, road-#24, nasirabad H/S, Chhittagong, flat size: 300 sq-ft, floor: A5(5th floor), room-category: 3 larg bed rooms, 2 bath rooms, 1 drawing, dining & family living room",
  },
  {
    "id": 5,
    "img": "https://i.ibb.co/T070ct1/Rectangle-404.png", 
    "name": "Epic Huda Palacio",
    "location": "Nasirabad H/S, Chattogram",
    "bedroom": " 3 Badrooms", 
    "bathroom":" 2 Bathrooms",
    "price" : 536,
    "img1" : "https://i.ibb.co/GRVkLTj/Rectangle-410.png",
    "img2" : "https://i.ibb.co/qCm8mmZ/Rectangle-407.png",
    "img3" : "https://i.ibb.co/R4Bn3qw/Rectangle-408.png", 
    "img4" : "https://i.ibb.co/PMfqvTC/Rectangle-409.png",
    "description": "3000 sq-ft, 3 bedrooms, semi-furnished, luxurious, south facing apartment for rent in nasirabad housing society, chittogong.",
    "priceDetails" : "Rent/Month : $550 (Negotiable) service Charge: 8000 tk per month, subject to change, security deposit: 3 month rent, Flat release policy: 3 months earlier notice required.  ",
    "property":" Address & area: Rang-malancha, house-#34, road-#24, nasirabad H/S, Chhittagong, flat size: 300 sq-ft, floor: A5(5th floor), room-category: 3 larg bed rooms, 2 bath rooms, 1 drawing, dining & family living room",
  },
  {
    "id": 6,
    "img": "https://i.ibb.co/rQhjHCd/Rectangle-405.png", 
    "name": "Rizwan Villa",
    "location": "Nasirabad H/S, Chattogram",
    "bedroom": " 3 Badrooms", 
    "bathroom":" 2 Bathrooms",
    "price" : 283,
    "img1" : "https://i.ibb.co/GRVkLTj/Rectangle-410.png",
    "img2" : "https://i.ibb.co/qCm8mmZ/Rectangle-407.png",
    "img3" : "https://i.ibb.co/R4Bn3qw/Rectangle-408.png", 
    "img4" : "https://i.ibb.co/PMfqvTC/Rectangle-409.png",
    "description": "3000 sq-ft, 3 bedrooms, semi-furnished, luxurious, south facing apartment for rent in nasirabad housing society, chittogong.",
    "priceDetails" : "Rent/Month : $550 (Negotiable) service Charge: 8000 tk per month, subject to change, security deposit: 3 month rent, Flat release policy: 3 months earlier notice required.  ",
    "property":" Address & area: Rang-malancha, house-#34, road-#24, nasirabad H/S, Chhittagong, flat size: 300 sq-ft, floor: A5(5th floor), room-category: 3 larg bed rooms, 2 bath rooms, 1 drawing, dining & family living room"
  }

]

export default apartments;

